blueprint:
  name: Temperature above threshold
  description: Send a notification if the temperature is above maximum temperature.
  domain: automation
  input:
    maximum_temperature:
      name: Maximum Temperature
      description: Maximum temperature
      selector:
        number:
          min: -150
          max: 150
    temperature_sensor:
      name: Temperature Sensor
      description: Temperature sensor to monitor
      selector:
        entity:
          filter:
            - domain: sensor
            - device_class: temperature
variables:
  maximum_temperature: !input maximum_temperature

trigger:
  - platform: numeric_state
    entity_id: !input temperature_sensor
    above: !input maximum_temperature
action:
  - service: notify.notify
    data:
      message: Garage Freezer Temperature is too high
  - service: notify.notify
    data_template:
      message: |
        {{trigger.entity_id }} Temperature is above {{ states('maximum_temperature') | default(0) }}.