blueprint:
  name: Temperature above threshold
  description: Send a notification if the temperature is above maximum temperature.
  domain: automation
  input:
    maximum_temperature:
      name: Maximum Temperature
      description: Maximum temperature
      selector:
        number:
          min: -150
          max: 150
    temperature_sensor:
      name: Temperature Sensor
      description: Temperature sensor to monitor
      selector:
        entity:
          filter:
            - domain: sensor
            - device_class: temperature

variables:
  threshold: !input maximum_temperature

trigger:
  - platform: numeric_state
    entity_id: !input temperature_sensor
    above: !input maximum_temperature
    for:
      minutes: 30

action:
  - service: notify.mobile_app_jeremys_iphone_13 #notify.notify
    data_template:
      message: |
        {{trigger.name }} Temperature is above {{ threshold | default(0) }}.
